from __future__ import annotations
import numpy

from numpy.typing import NDArray
from typing import overload, Annotated

from . import RandomNumberGenerator
from .distributions import Distribution
from .polynomials import PolynomialFamily

__all__: list[str] = ['ComposedQuadrature', 'MonteCarloTransformation', 'PCE_Transformation', 'PointTransformation', 'StirlingInterpolationFirstOrder', 'StirlingInterpolationSecondOrder', 'UnscentedTransformation']

class PointTransformation:
    def mean(self, points: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def covariance(self, pointsX: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], pointsY: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    def variance(self, points: Annotated[NDArray[numpy.float64], "[1, n]"]) -> float:
        ...
    def mean1D(self, points: Annotated[NDArray[numpy.float64], "[1, n]"]) -> float:
        ...
    def dmean_dpoints_vec(self, vec: Annotated[NDArray[numpy.float64], "[m, 1]"]) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def dcov_dpointsX_vec(self, pointsX: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], pointsY: Annotated[NDArray[numpy.float64], "[m, 1]"]) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def dcov_dpointsY_vec(self, pointsX: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], pointsY: Annotated[NDArray[numpy.float64], "[m, 1]"]) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def dpoints_dmean_vec(self, vec: Annotated[NDArray[numpy.float64], "[m, 1]"]) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def dpoints_dcov_vec(self, covCholesky: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], vec: Annotated[NDArray[numpy.float64], "[m, 1]"]) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    def dmean1D_dpoints(self) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def dvar_points(self, points: Annotated[NDArray[numpy.float64], "[1, n]"]) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...
    def number_of_points(self) -> int:
        ...

class ComposedQuadrature(PointTransformation):
    @overload
    def __init__(self, dimX: int, dimY: int, polyFamily: list[PolynomialFamily], quadratureOrder: Annotated[NDArray[numpy.int32], "[m, 1]"]) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, polyFamily: list[PolynomialFamily], quadratureOrder: list[int]) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, polyFamily: list[PolynomialFamily], quadratureOrder: int) -> None:
        ...
    def normalized_points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, dist: Distribution) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, mean: Annotated[NDArray[numpy.float64], "[m, 1]"], covCholesky: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    def roots(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    def weights(self) -> Annotated[NDArray[numpy.float64], "[m, 1]"]:
        ...

class MonteCarloTransformation(PointTransformation):
    def __init__(self, dimX: int, dimY: int, numberOfPoints: int, rng: RandomNumberGenerator) -> None:
        ...
    @overload
    def points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, dist: Distribution) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    def set_point(self, index: int, newPoint: Annotated[NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...

class PCE_Transformation(PointTransformation):
    @overload
    def __init__(self, dimX: int, dimY: int, polyFamily: list[PolynomialFamily], maxPolyOrder: int, quadratureOrder: Annotated[NDArray[numpy.int32], "[m, 1]"]) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, polyFamily: list[PolynomialFamily], maxPolyOrder: int, quadratureOrder: list[int]) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, polyFamily: list[PolynomialFamily], maxPolyOrder: int, quadratureOrder: int) -> None:
        ...
    @overload
    def points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, dist: Distribution) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...

class StirlingInterpolationFirstOrder(PointTransformation):
    @overload
    def __init__(self, dimX: int, dimY: int, stepSize: float, considerUncertain: list[bool]) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, stepSize: float) -> None:
        ...
    @overload
    def points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, dist: Distribution) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, mean: Annotated[NDArray[numpy.float64], "[m, 1]"], covCholesky: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
        
class StirlingInterpolationSecondOrder(PointTransformation):
    @overload
    def __init__(self, dimX: int, dimY: int, stepSize: float, considerUncertain: list[bool]) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, stepSize: float) -> None:
        ...
    @overload
    def points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, dist: Distribution) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, mean: Annotated[NDArray[numpy.float64], "[m, 1]"], covCholesky: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
        
class UnscentedTransformation(PointTransformation):
    @overload
    def __init__(self, dimX: int, dimY: int, alpha: float, beta: float, kappa: float) -> None:
        ...
    @overload
    def __init__(self, dimX: int, dimY: int, alpha: float, beta: float, kappa: float, considerUncertain: list[bool]) -> None:
        ...
    @overload
    def points(self) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, dist: Distribution) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
    @overload
    def points(self, mean: Annotated[NDArray[numpy.float64], "[m, 1]"], covCholesky: Annotated[NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> Annotated[NDArray[numpy.float64], "[m, n]"]:
        ...
